### ISSUE TITLE
PDF version in the git repository

### ISSUE THREAD

**Issue by newlog** [crypto101/book#206]
Hello,

What do you think about hosting the PDF version, not only the tex sources, in the github repository. Updating that PDF version once a week or after some changes.

I know that I can download the PDF from https://www.crypto101.io/ but I don't know if that version has been updated recently (when) with the changes of the repository (what).

Great work,
newlog.

**Comment by MartyMacGyver** [comment]
I'd like to second this, especially since building the book is not trivial (a sentiment that is reinforced in the Readme). Even hosting the PDF (with identifying information in it or in the title) would be a plus - do you generally rebuild the PDF when pulling changes?

(Also, having that version and hash on the copyright page would be a little more consistent than where it is now.)

**Comment by lvh** [comment]
@MartyMacGyver Thanks for your feedback! I'm not sure I understand what you mean by "consistency"; I'm assuming that by "where it is now" you mean in the PDF?

Difficulty building is a totally valid concern, but hosting the PDF doesn't really help with that. A Dockerfile (and perhaps a `make push` to automatically update to the newest version), would alleviate those concerns though.

**Comment by lvh** [comment]
@MartyMacGyver Re hosting with identifying information: I'm assuming you've seen https://www.crypto101.io/ , which hosts the PDF on a CDN, and the PDF has identifying information (commit &c) in it.

**Comment by MartyMacGyver** [comment]
By consistency I mean having the version info on the copyright page, versus several pages into the book.

As for the hosting, it would be useful to have the version stated on the website (rather than needing to download and inspect the PDF to determine how fresh it actually is).

The core question I have is, how often do you actually build the PDFs, even if you don't necessarily upload them? Regularly with pulls or rarely?

**Comment by lvh** [comment]
That sounds like a few distinct issues, and all of them only incidentally related to a PDF being in the repo. It sounds like the only real feature there is that Github would tell you when it was last updated, right? I current rebuild and upload a new PDF to the CDN whenever a significant amount of change has occurred; that's usually marginally less often than every PR. Assuming that frequency doesn't change, it doesn't really matter where the PDF lives, right?

It sounds like a better solution would be to automate that process, and have CI build the PDF every time a commit gets pushed, then publish it to the CDN, and update the webpage. Does that sound about right?

Either way, step one sounds like resolving the tricky build environment bit. Things have changed quite a bit since that was originally written; specifically, you can build the PDF with stable releases of org-mode and Emacs now. A Dockerfile sounds like a reasonable resolution. Once that's done, Travis can build and upload the PDF, as well as upload the Github Pages site. That sounds like a lot of work overall, but most of it seems  like it can be done independently.

**Comment by MartyMacGyver** [comment]
I wasn't meaning to make more work for you - all other things aside, it just sounded like it'd be low overhead and worthwhile to update the PDF on the website if not on github when you re-generate it.
