### ISSUE TITLE
7.5 slight confussion

### ISSUE THREAD

**Issue by colwem** [crypto101/book#271]
It says that Mallory manages to get her hands on all the rows of a table.  I understand this to mean that she has a snapshot of the table at a particular time but doesn't have ongoing access to it.  The attack requires her to get access to a new piece of encrypted data that the server will create and store.  But she doesn't have ongoing access right?  So I guess either that's not true and she does have access to the table or she's getting the server to encrypt her message and then send that encrypted message to her rather than just storing it. 

It would have been easier for me to understand this attack had this been explicitly clarified.  I wouldn't characterize this as something that made me not understand the material but rather something that made me unsure as to whether I was completely understanding it.

Actually through the book so far I feel like the things I tend to have the most confusion about is what's public and what's not and what the attacker does and does not know.  I can usually figure it out by re-reading the sections more carefully but if you want to make things easier to follow I think making this stuff more obvious would help.  Like for instance I'm reading the section on CTR right now and right from the start I'm wondering, wait is the nonce public? Is it sent with the message?  I guess it must be but I'm not sure.  

I was thinking the same kind of things with IV's.  Are they public?  You did mention that they were given alongside the encrypted message sometimes.  But why sometimes?  I can't understand how it could be decrypted unless the IV was transmitted with the message or it was secret.  But if it's secret then it's just another key isn't it?  And if it's public then how could using the key as the IV have ever made any sense?   That exploit seems pretty redundant when you've already been given the key.  Anyway, these kinds of thoughts distract me from the reading.

**Comment by lvh** [comment]
Thanks for your feedback! There seem to be some instances of a general problem here. I'll try and deal with those first; if I can figure out how to clarify it for you, perhaps we can translate that to the book.

The predictable IV attack presented in 7.5 does assume Mallory can see the ciphertext. That is strictly true in the formal mathematical security model (which the book currently doesn't really talk about). It is often de facto true for an attack as described in that section, but I haven't found a way to communicate that effectively without waving my hands vigorously and simply asserting that is the case. I suppose in this case saying that Mallory can just extract the ciphertexts continuously would be both a comprehensible and realistic scenario.

One challenge is that protocols differ (notably a lot of them get it wrong). Part of the deal with Crypto 101 is that I try to teach how cryptosystems work by also illustrating how they (bad ones) fail. The security requirements of CTR nonces and CBC IVs are inherent to the mode (nonces must not be re-used, IVs must not be predictable), but how you achieve that is part of the protocol, and those can differ. 
IVs are sometimes provided in the protocol because IVs should be unpredictable, not secret. If _might_ be a secret too, but it's not necessary; you can just pass it along with a message as you can with CTR nonces. Secret is also not sufficient, which is what the IV=key problem illustrates. You could also _generate_ the IVs in a secure fashion  so that they can be elided from the protocol (say, generate them from a key that you agreed on) and still end up with a secure system. (This is exceedingly rare, because anyone who cares enough about that will probably use an AEAD mode rather than CBC mode.).

Similarly, nonces can be provided in the protocol, but they could also be elided. For example, if your protocol knows that only _exactly_ one message will be encrypted for a given key, then using the same nonce all the time is perfectly fine. This is something I do in [icecap][fixednonce], for example. If you know that you're the only interaction to use a particular key, you can just increment the nonce for each message (or, say, subsequent odd numbers for messages being sent from A to B, and subsequent even numbers for the other direction). You can do that because both sides know the nonce anyway, so you don't have to communicate it. You _can_ communicate it (again, the security requirement is that it's used once, not that it's secret), and many systems do.

The standard rule for both of these is to generate them cryptographically random. That's definitely fine for IVs (a la CBC), and it's also fine for nonces (a la CTR) assuming that nonces are sufficiently big that they're unlikely to collide. For example, in the Salsa family of ciphers (Salsa, ChaCha, XSalsa), XSalsa is just Salsa with a bigger nonce, done for the sole purpose of making sure that random nonces are OK. Nonce reuse for random nonces in GCM is only a problem when you have a terrible random number generator; but there are standards that attempt to address this, like AES-GCM-SIV (https://eprint.iacr.org/2015/102.pdf).

[fixednonce]: https://github.com/lvh/icecap/blob/master/src/icecap/crypto.clj#L118

**Comment by lvh** [comment]
I'm closing this since I answered it, but please comment with specific feedback if you have any.
