### ISSUE TITLE
Error in inductive formula for H_j (Montgomery ladder)

### ISSUE THREAD

**Issue by vicariggio** [crypto101/book#289]
On page 220 (in pdf based on a596660):
![montgomery formula](https://cloud.githubusercontent.com/assets/20338548/16653598/dc8b359e-4451-11e6-85c8-c26578513039.png)
The k_j = 1 case for the inductive formula for H_j has two contradicting versions. I'm not entirely sure, but it seems the latter is the correct one (the math doesn't seem to check out with the first one).

**Comment by lvh** [comment]
(a) Hj = Lj + 1
(b) Lj = 2*L(j+1) + kj
(c) kj = 1

(b, c) => (d): Lj = 2*L(j+1) + 1
(a, d) => (e): Hj = 2*L(j+1) + 2

... which definitely isn't what that says :)

What it should have said, is, as you pointed out, 2H(j+1), because:

(f): Lj = Hj − 1
(e, f) => (g): Hj = 2*L(j+1) + 2 = 2*H(j+1) - 2 + 2

Good catch!
