### ISSUE TITLE
Why are permutations relevant?

### ISSUE THREAD

**Issue by trackpick** [crypto101/book#324]
In Block Ciphers: Description, can you explain why the block cipher is a permutation? I think it needs to be because no two blocks are allowed to map to the same block (or you wouldn't be able to do the inverse for decryption). So you have n choices to map the first block to, n-1 to map the second block to, etc?

**Comment by eenblam** [comment]
> because no two blocks are allowed to map to the same block (or you wouldn't be able to do the inverse for decryption)

In short, yes. If we don't have this, the message becomes harder to reliably recover for the intended recipient(s), without necessarily being any harder for an attacker to partially recover (and to ill effect.)

Another reason for this is **key size** (and **key reuse** as a result.) If our key is smaller than our data, we need to reuse it to encrypt everything, and it happens to be a pain to generate and share big keys. Block ciphers allow us to reuse a key a number of times, so we can pick a key length that is much smaller than our message length. This is possible by spreading information from each block into subsequent blocks encrypted with the same key, and (when done correctly) this makes it harder to recover information about our key (which is being reused!) by comparing blocks. *(If that last sentence is a bit off-base, real crypto people please chime in!)*
This property is [confusion](https://en.wikipedia.org/wiki/Diffusion_(cryptography)) - the extent to which any given part of the cipher text depends on multiple parts of the key. We can accomplish this by permuting a block element then using the output of that permutation to determine the next permutation.

Since we wish to combine a lot of things of the same size, and we don't know how many things we'll be combining, the problem would be rather difficult to address if we didn't have consistent sizes going into and out of the block algorithm. So, being able to describe an arbitrary number of steps as a single map from a (block, key) pair to a single output block of the same size gives us a sensible way of reusing our key an arbitrary number of times without exposing nearly as much information about it.

**Comment by lvh** [comment]
@eenblam You're right about the critical property of a permutation being that you can un-permute it. 

The bit about key size and key reuse seems pretty confusing to me, and only relevant if you're starting from one-time-pads. Re: information spreading: that's not really an intrinsic property. The most popular block cipher modes (CBC and CTR) only use the most recent block and the previous block; they don't have the property that a bogus block corrupts the rest of the decryption (which, unless I misunderstood you, would be evidene of the "spreading information into subsequent blocks"). I'd be careful to call that confusion (and generally avoid diffusion/confusion); you do not need a mode that spreads information around in the ctext in order to get confusion in AES: AES always does that. Block cipher modes do not make a part of the message more or less dependent on the key; they only make a part of the message more or less dependent on the other, contextual blocks in the message.

I'm not sure I follow with this sentence:

> So, being able to describe an arbitrary number of steps as a single map from a (block, key) pair to a single output block of the same size gives us a sensible way of reusing our key an arbitrary number of times without exposing nearly as much information about it.

That suggests that key recovery attacks are a function of varying block size?

**Comment by trackpick** [comment]
@eenblam thanks for the explanation!

**Comment by eenblam** [comment]
@lvh Thanks for chiming in! I crossed out some of the more erroneous information in my previous post.

> The bit about key size and key reuse seems confusing to me, and only relevant if you're starting from one-time-pads.

The book discussed one-time pads immediately prior, so I thought this was appropriate.

However, you're right that the rest of the post is rather confusing (and misleading for those who don't know better.

While writing, my internal narrative was something like this...

"We've seen repeating-key-XOR, which was our first answer to the question, "Can I use a key size smaller than my message size?" This went pretty badly, but maybe we can improve on this idea of splitting the message into equal length blocks. We can come up with different schemes to meet different priorities..."

...which I think is a reasonable way to segue into block ciphers. Start with repeating-key-XOR as "XOR over ECB," then move on since we already know it's terrible. Somehow, though, I managed to say a lot of gibberish instead. You all have my word that, in the future, I will refrain from trying to answer crypto questions before getting out of bed. :)

> Re: information spreading:  (...) There are exceptions, like PCBC, but they're definitely rare (...)

Yes. I did have PCBC on the brain, and I did overgeneralize.

> I'd be careful to call that confusion (and generally avoid diffusion/confusion); (...) Confusion and diffusion are terms that are generally kept for discussing the underlying primitive, like a hash or a block cipher.

Cool! Thanks for straightening me out on that as well. It sounds like I was misapplying the terminology, but I was expecting there to be at least some element of confusion at work since CBC, PCBC, CFB, and OFB (neglecting CTR) all incorporate some amount of information from the key in the previous block (more in the case of PCBC.) (So, I was specifically talking about choice of block cipher, but doing a very bad job of establishing that.) Is this still a poor interpretation on my part?

**Comment by lvh** [comment]
Yep, OK, that context makes sense; but I definitely wouldn't elide it :)

Re: some element of confusion; the term confusion specifically deals with locality in the key versus locality in the message; which is a property every block cipher intrinsically does these days. Because I'm not trying to teach anyone how to design a PRF or PRP, that's mostly out of scope.

 The point of block cipher modes is to produce something that will encrypt a stream. In order to do that, and to not get an ECB-like problem where an attacker can spot repeated encryptions, you can't have collisions in your inputs to your block cipher. Different modes achieve that in different ways; which might shed some light on why a lot of cryptographers find CTR so elegant: _of course_ it produces different output blocks, that's literally the only thing it could do. That also illustrates why e.g. CBC attacks can typically be "moved" down the ciphersuite, how SWEET32 works, &c.

I'm not sure I'd agree that modes like CFB, OFB, CTR... incorporate _key material_ in a block. That kind of muddles the line between modes and ciphers. The security proofs only care that something is, e.g., a PRP -- it does not say that you have to use a key to build it. Of course, there usually is going to be a key because that's just the most convenient way to get a PRP, but I'd be careful about muddying those concepts. I think it'd be more accurate to just state that all secure block cipher modes try to make sure that block cipher inputs are unique. All of those modes are agnostic to the key, but what they can do is try and produce unique inputs to the PRP (because, key or not, a PRP is still a pure function, so collisions in the input will produce collisions in the output).
