### ISSUE TITLE
Download link is currently broken on the site

### ISSUE THREAD

**Issue by ntoshev** [crypto101/book#329]
https://9d0df72831e4b345bb93-4b37fd03e6af34f2323bb971f72f0c0d.ssl.cf5.rackcdn.com/Crypto101.pdf returns 404

**Comment by lvh** [comment]
Thanks! I'm on it :)

**Comment by lvh** [comment]
Should be fixed now! Thanks for the report.

Here's what happened:

- Rackspace unilaterally and without warning changed their open source plans. Even though the C101 account is real cheap (it only serves that one PDF from CDN and only a handful of times because usually CloudFlare gets it), they have minimum account fees, so....
- I changed master, but not gh-pages, because this is my new laptop and I'm an idiot -- so  the page never updated.

Fixed now.

**Comment by ntoshev** [comment]
Awesome, thank you!
