### ISSUE TITLE
Chapter 7, pg 66 ("Discovering the padding length") -- why start from the left-hand side of the block?

### ISSUE THREAD

**Issue by crawsible** [crypto101/book#342]
Hi there, thanks for putting this book together!

This isn't so much an inaccuracy as an observation. The mechanism by which padding length is found on page 66 seems counterintuitive. If `... xx xx  xx 01` is the likeliest valid padding, and an attacker is attempting to find the size of the padding, why not start by altering the second-to-last byte in the block? If the valid padding oracle returns true in that case (as will be the case ~99.8% of the time), they will immediately know the padding length is 1, and if not, they can next alter the third-to-last byte to determine whether the padding length is 2, etc.

**Comment by lvh** [comment]
Yep, that works too. I've found that it's marginally trickier to show/implement because you don't just get to perpetually mess with the same block (each experiment has to be discarded after you try it, or at least your change undone) and the stop condition is a little more complicated (you're trying to get it to pass, instead of waiting for it to fail), whereas in the left-to-right case you just to get to XOR each byte until the oracle stops accepting.

**Comment by crawsible** [comment]
Ah, that makes sense. Thanks!

**Comment by lvh** [comment]
FWIW I'm pretty happy to add a paragraph to clear this up :)

**Comment by lvh** [comment]
^ fixed in reffed commit, let me know if there are issues with that language. Thanks for your contribution :)

**Comment by crawsible** [comment]
Awesome, happy to have contributed in some small way. I left a comment on what looked to be a slight typo; otherwise looks good!
